// frontend/src/pages/Register.tsx
import React, { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { Layout } from 'lucide-react';
import api from '../api/axios';
import { useAuthStore } from '../store/authStore';

export const Register: React.FC = () => {
  const [formData, setFormData] = useState({ name: '', email: '', password: '', role: 'USER' });
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  
  const login = useAuthStore(state => state.login);
  const navigate = useNavigate();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      // 1. Registrar
      await api.post('/auth/register', formData);
      // 2. Auto-login tras registro exitoso
      const response = await api.post('/auth/login', { email: formData.email, password: formData.password });
      login(response.data.token, response.data.data);
      navigate('/dashboard');
    } catch (err: any) {
      setError(err.response?.data?.message || 'Error al registrar usuario');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center p-4">
      <div className="glass-panel p-8 rounded-2xl w-full max-w-md relative overflow-hidden">
        {/* Glow effect */}
        <div className="absolute -left-20 -top-20 w-40 h-40 bg-secondary/20 rounded-full blur-3xl pointer-events-none"></div>
        
        <div className="relative z-10">
          <div className="flex justify-center mb-6">
            <div className="bg-secondary/20 p-3 rounded-xl text-secondary">
              <Layout size={32} />
            </div>
          </div>
          
          <h2 className="text-2xl font-bold text-center text-text mb-2">Crear Cuenta</h2>
          <p className="text-center text-text-secondary mb-8">Únete a TaskFlow y organiza tus proyectos</p>

          {error && (
            <div className="bg-danger/20 border border-danger/50 text-danger px-4 py-3 rounded-lg text-sm mb-6">
              {error}
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-text-secondary mb-1">Nombre</label>
              <input 
                type="text" 
                required
                value={formData.name}
                onChange={e => setFormData({...formData, name: e.target.value})}
                className="w-full bg-surface border border-border rounded-lg px-4 py-2.5 text-text focus:ring-2 focus:ring-secondary/50 focus:border-secondary outline-none transition-all"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-text-secondary mb-1">Email</label>
              <input 
                type="email" 
                required
                value={formData.email}
                onChange={e => setFormData({...formData, email: e.target.value})}
                className="w-full bg-surface border border-border rounded-lg px-4 py-2.5 text-text focus:ring-2 focus:ring-secondary/50 focus:border-secondary outline-none transition-all"
              />
            </div>
            
            <div>
              <label className="block text-sm font-medium text-text-secondary mb-1">Contraseña</label>
              <input 
                type="password" 
                required
                value={formData.password}
                onChange={e => setFormData({...formData, password: e.target.value})}
                className="w-full bg-surface border border-border rounded-lg px-4 py-2.5 text-text focus:ring-2 focus:ring-secondary/50 focus:border-secondary outline-none transition-all"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-text-secondary mb-1">Rol</label>
              <select 
                value={formData.role}
                onChange={e => setFormData({...formData, role: e.target.value})}
                className="w-full bg-surface border border-border rounded-lg px-4 py-2.5 text-text focus:ring-2 focus:ring-secondary/50 focus:border-secondary outline-none transition-all"
              >
                <option value="USER">Usuario Estándar</option>
                <option value="ADMIN">Administrador</option>
              </select>
            </div>

            <button 
              type="submit" 
              disabled={loading}
              className="w-full bg-secondary hover:bg-secondary/90 text-white font-medium py-2.5 rounded-lg transition-all shadow-lg shadow-secondary/25 disabled:opacity-70 mt-4"
            >
              {loading ? 'Creando cuenta...' : 'Registrarse'}
            </button>
          </form>

          <p className="text-center text-sm text-text-secondary mt-6">
            ¿Ya tienes cuenta? <Link to="/login" className="text-secondary hover:underline">Inicia sesión</Link>
          </p>
        </div>
      </div>
    </div>
  );
};

// frontend/src/app/components/auth/register.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  template: `
    <div class="auth-page">
      <div class="auth-card">
        <div class="auth-header">
          <span class="auth-icon">⚡</span>
          <h1>Crear Cuenta</h1>
          <p>Únete a TaskFlow y gestiona tus proyectos</p>
        </div>

        <form (ngSubmit)="onRegister()" class="auth-form">
          <div class="form-group">
            <label for="name">Nombre Completo</label>
            <input type="text" id="name" class="form-control" [(ngModel)]="name" name="name" placeholder="Tu nombre" required />
          </div>

          <div class="form-group">
            <label for="email">Correo Electrónico</label>
            <input type="email" id="email" class="form-control" [(ngModel)]="email" name="email" placeholder="tu@correo.com" required />
          </div>

          <div class="form-group">
            <label for="password">Contraseña</label>
            <input type="password" id="password" class="form-control" [(ngModel)]="password" name="password" placeholder="Mínimo 6 caracteres" required />
          </div>

          <div class="form-group">
            <label for="role">Rol</label>
            <select id="role" class="form-control" [(ngModel)]="role" name="role">
              <option value="DEVELOPER">Desarrollador</option>
              <option value="PROJECT_MANAGER">Project Manager</option>
              <option value="ADMIN">Administrador</option>
            </select>
          </div>

          <div class="error-message" *ngIf="error">{{ error }}</div>

          <button type="submit" class="btn btn-primary btn-block" [disabled]="loading">
            {{ loading ? '⏳ Registrando...' : '✨ Crear Cuenta' }}
          </button>
        </form>

        <div class="auth-footer">
          <p>¿Ya tienes cuenta? <a routerLink="/login">Inicia sesión</a></p>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .auth-page {
      display: flex;
      align-items: center;
      justify-content: center;
      min-height: calc(100vh - 64px);
    }

    .auth-card {
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: 24px;
      padding: 48px;
      width: 100%;
      max-width: 440px;
      box-shadow: 0 20px 60px var(--shadow);
    }

    .auth-header {
      text-align: center;
      margin-bottom: 36px;
    }

    .auth-icon { font-size: 3rem; display: block; margin-bottom: 12px; }

    .auth-header h1 {
      font-size: 2rem;
      font-weight: 800;
      background: linear-gradient(135deg, var(--primary), var(--accent));
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      background-clip: text;
      margin-bottom: 8px;
    }

    .auth-header p { color: var(--text-secondary); font-size: 0.9rem; }
    .auth-form { margin-bottom: 24px; }
    .btn-block { width: 100%; justify-content: center; padding: 14px; font-size: 1rem; }

    .error-message {
      background: rgba(239, 68, 68, 0.1);
      border: 1px solid rgba(239, 68, 68, 0.3);
      color: var(--danger);
      padding: 12px 16px;
      border-radius: 10px;
      font-size: 0.85rem;
      margin-bottom: 16px;
    }

    .auth-footer { text-align: center; font-size: 0.875rem; color: var(--text-secondary); }
    .auth-footer a { font-weight: 600; }
  `]
})
export class RegisterComponent {
  name = '';
  email = '';
  password = '';
  role = 'DEVELOPER';
  error = '';
  loading = false;

  constructor(private authService: AuthService, private router: Router) {}

  onRegister(): void {
    this.loading = true;
    this.error = '';

    this.authService.register(this.name, this.email, this.password, this.role).subscribe({
      next: (response) => {
        this.loading = false;
        if (response.success) {
          this.router.navigate(['/dashboard']);
        }
      },
      error: (err) => {
        this.loading = false;
        this.error = err.error?.message || 'Error al registrarse';
      }
    });
  }
}
